In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel
pd.pandas.set_option('display.max_columns', None)

In [2]:
dataset=pd.read_csv('X_train.csv')

In [3]:

dataset.head()

,Id,SalePrice,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,1,12.247694,-0.118331,-1.486714,-1.663936,-0.115226,-0.132812,0.000002,0.016689,4.785156e-08,3.926844e-09,0.0,1.176719e-08,3.752754e-09,-2.980348,9.698347e-08,0.0,-2.710600,0.037037,0.000,0.074074,0.125,0.005859,0.037037,-0.177083,0.000000,0.000004,0.031250,1.921993e-07,0.000000e+00,3.727073e-07,0.000000,0.0,0.0,0.0,0.0,-0.098422,-626.843750,0.0,0.0,0.0
1,2,12.109011,-0.118339,-1.476184,-1.662979,-0.116598,-0.126953,0.000012,0.016803,0.000000e+00,5.439736e-09,0.0,2.227921e-08,5.532682e-09,-2.959310,0.000000e+00,0.0,-2.724049,0.000000,0.125,0.074074,0.000,0.005859,0.037037,-0.178241,0.037037,0.000025,0.031250,1.613352e-07,4.734496e-07,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,-0.096168,-626.859375,0.0,0.0,0.0
2,3,12.317167,-0.118331,-1.484426,-1.661790,-0.115226,-0.132812,0.000003,0.016693,3.955078e-08,2.703182e-09,0.0,3.404640e-08,4.033334e-09,-2.976440,9.834623e-08,0.0,-2.708675,0.037037,0.000,0.074074,0.125,0.005859,0.037037,-0.178241,0.037037,0.000006,0.031250,2.132431e-07,0.000000e+00,2.566181e-07,0.000000,0.0,0.0,0.0,0.0,-0.093163,-626.843750,0.0,0.0,0.0
3,4,11.849398,-0.118329,-1.490773,-1.663019,-0.115226,-0.132812,0.000036,0.016825,0.000000e+00,1.201414e-09,0.0,4.236188e-08,3.314348e-09,-2.974077,8.585422e-08,0.0,-2.710419,0.037037,0.000,0.037037,0.000,0.005859,0.037037,-0.177662,0.037037,0.000007,0.046875,2.251678e-07,0.000000e+00,2.138484e-07,0.000002,0.0,0.0,0.0,0.0,-0.098422,-626.875000,0.0,0.0,0.0
4,5,12.429216,-0.118331,-1.473710,-1.660013,-0.113855,-0.132812,0.000003,0.016702,8.544922e-08,3.643177e-09,0.0,3.843949e-08,5.019747e-09,-2.964583,1.195827e-07,0.0,-2.699486,0.037037,0.000,0.074074,0.125,0.007812,0.037037,-0.176505,0.037037,0.000007,0.046875,2.932092e-07,3.050414e-07,5.132362e-07,0.000000,0.0,0.0,0.0,0.0,-0.090909,-626.843750,0.0,0.0,0.0

In [4]:
y_train=dataset[['SalePrice']]

In [5]:
X_train=dataset.drop(['Id','SalePrice'],axis=1)

In [6]:
sel_ = SelectFromModel(Lasso(alpha=0.0001, random_state=0))
sel_.fit(X_train, y_train)

selected_features = X_train.columns[sel_.get_support()]

# total features
print('total features: {}'.format(X_train.shape[1]))
print('selected features: {}'.format(len(selected_features)))
print('features with coefficients shrank to zero: {}'.format(
    np.sum(sel_.estimator_.coef_ == 0)))

total features: 39
selected features: 15
features with coefficients shrank to zero: 24

In [7]:
sel_.get_support()

array([False,  True, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False,  True,  True,  True,
        True,  True, False,  True, False,  True, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True])

In [8]:
for alpha in [0.005, 0.001, 0.0005, 0.0001]:
    model = SelectFromModel(Lasso(alpha=alpha, random_state=0))
    model.fit(X_train, y_train)
    n = model.get_support().sum()
    print(f"alpha={alpha} → {n} features selected")

alpha=0.005 → 2 features selected
alpha=0.001 → 8 features selected
alpha=0.0005 → 9 features selected
alpha=0.0001 → 15 features selected

In [9]:
selected_feat = X_train.columns[sel_.get_support()]
selected_feat

Index(['LotFrontage', 'OverallQual', '1stFlrSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'KitchenAbvGr', 'Fireplaces',
       'GarageCars', 'YrSold', 'LotFrontage_nan', 'MasVnrArea_nan',
       'GarageYrBlt_nan'],
      dtype='str')

In [10]:
for alpha in [0.00005, 0.00001, 0.000005, 0.000001]:
    model = SelectFromModel(Lasso(alpha=alpha, random_state=0))
    model.fit(X_train, y_train)
    n = model.get_support().sum()
    print(f"alpha={alpha} → {n} features selected")

alpha=5e-05 → 17 features selected
alpha=1e-05 → 17 features selected
alpha=5e-06 → 17 features selected
alpha=1e-06 → 19 features selected

In [11]:
X_train=X_train[selected_feat]

In [12]:
# Finalize with alpha=0.0001
feature_sel_model = SelectFromModel(Lasso(alpha=0.0001, random_state=0))
feature_sel_model.fit(X_train, y_train)

# See which features were selected
selected_features = X_train.columns[feature_sel_model.get_support()]
print("Selected features:", selected_features.tolist())
print("Total:", len(selected_features))

# Filter your dataset
X_train_selected = feature_sel_model.transform(X_train)
print("New X_train shape:", X_train_selected.shape)

Selected features: ['LotFrontage', 'OverallQual', '1stFlrSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'KitchenAbvGr', 'Fireplaces', 'GarageCars', 'YrSold', 'LotFrontage_nan', 'MasVnrArea_nan', 'GarageYrBlt_nan']
Total: 15
New X_train shape: (1460, 15)

In [13]:

X_train.head()

,LotFrontage,OverallQual,1stFlrSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,KitchenAbvGr,Fireplaces,GarageCars,YrSold,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,-1.486714,-0.115226,-2.980348,-2.710600,0.037037,0.000,0.074074,0.125,0.037037,0.000000,0.031250,-626.843750,0.0,0.0,0.0
1,-1.476184,-0.116598,-2.959310,-2.724049,0.000000,0.125,0.074074,0.000,0.037037,0.037037,0.031250,-626.859375,0.0,0.0,0.0
2,-1.484426,-0.115226,-2.976440,-2.708675,0.037037,0.000,0.074074,0.125,0.037037,0.037037,0.031250,-626.843750,0.0,0.0,0.0
3,-1.490773,-0.115226,-2.974077,-2.710419,0.037037,0.000,0.037037,0.000,0.037037,0.037037,0.046875,-626.875000,0.0,0.0,0.0
4,-1.473710,-0.113855,-2.964583,-2.699486,0.037037,0.000,0.074074,0.125,0.037037,0.037037,0.046875,-626.843750,0.0,0.0,0.0

In [14]:
import pandas as pd

# Directly filter X_train columns using selected_features
X_train_selected = X_train[selected_features]

print(X_train_selected.shape)
X_train_selected.head()

(1460, 15)

,LotFrontage,OverallQual,1stFlrSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,KitchenAbvGr,Fireplaces,GarageCars,YrSold,LotFrontage_nan,MasVnrArea_nan,GarageYrBlt_nan
0,-1.486714,-0.115226,-2.980348,-2.710600,0.037037,0.000,0.074074,0.125,0.037037,0.000000,0.031250,-626.843750,0.0,0.0,0.0
1,-1.476184,-0.116598,-2.959310,-2.724049,0.000000,0.125,0.074074,0.000,0.037037,0.037037,0.031250,-626.859375,0.0,0.0,0.0
2,-1.484426,-0.115226,-2.976440,-2.708675,0.037037,0.000,0.074074,0.125,0.037037,0.037037,0.031250,-626.843750,0.0,0.0,0.0
3,-1.490773,-0.115226,-2.974077,-2.710419,0.037037,0.000,0.037037,0.000,0.037037,0.037037,0.046875,-626.875000,0.0,0.0,0.0
4,-1.473710,-0.113855,-2.964583,-2.699486,0.037037,0.000,0.074074,0.125,0.037037,0.037037,0.046875,-626.843750,0.0,0.0,0.0